Categories:
  - System
License: Apache-2.0
SourceCode: https://bitbucket.org/oF2pks/fdroid-applications-info/src/master/
IssueTracker: https://bitbucket.org/oF2pks/fdroid-applications-info/pull-requests/

Name: apps_Packages Info
AutoName: apps_Packages Info
Summary: Fork of ApplicationsInfo; SharedLibs, uid, +Persistent +Stopped +Inactive
    +Suspended per app & READ_LOGS ...
Description: |-
    Updated ApplicationsInfos with colors & mini-tags (and basic fixes), to 
    Quickly show all possible android states for all installed packages:

    * SharedLibs & uid added
    * Persistent +Stopped +Inactive +Suspended state per app
    * debug or test possible flavour
    * sdk version
    * READ_LOGS if granted
    * system app with locked data
    * ALL ApplicationInfos classic features
    * (wip full scan classes & trackers)

    With minimum of permissions, this app also demonstrates all possible leaks 
    that can be done by any installed app with INTERNET granted (and closed
    sources), in order to grab data for profiling.

    (prim-origin https://github.com/MajeurAndroid/Android-Applications-Info)

RepoType: git
Repo: https://bitbucket.org/oF2pks/fdroid-applications-info/src/master/

Builds:
  - versionName: 1.7-9
    versionCode: 9
    commit: v1.7-9
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
CurrentVersion: 1.7-9
CurrentVersionCode: 9
