name: Sync with GitLab
on:
    # schedule:
    #     - cron: "0 0 * * *"
    push:
jobs:
    Sync:
        name: Mirror from GitHub to GitLab
        runs-on: ubuntu-latest
        env:
            GITLAB_TOKEN: ${{ secrets.GITLAB_PASSWORD }}
        steps:
            # - uses: actions/checkout@v4
            - name: Setup
              continue-on-error: true
              run: |
                git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
                git config --global user.name "Mohamed Hisham Abdelzaher"
                git clone --bare "https://github.com/$GITHUB_REPOSITORY" .
                # git config pull.rebase false
            - name: Verify
              continue-on-error: true
              run: |
                ls -a
                # rm renovate.json
                # rm -rd .github
                git remote -v
                git fetch -p origin
                git branch -a
            - name: Update
              continue-on-error: true
              run: |
                # git switch com.mh0386.anynotedotai
                # git add .
                # git commit -m "Update com.MH0386.AnyNoteDotAI.yml"
                # git pull --allow-unrelated-histories
                git push --mirror "https://MH0386:$GITLAB_TOKEN@gitlab.com/MH0386/fdroiddata.git"
