name: Sync with GitLab
on:
    schedule:
        - cron: "0 0 * * *"
    push:
jobs:
    Sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup
              continue-on-error: true
              run: |
                git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
                git config --global user.name "Mohamed Hisham Abdelzaher"
                git remote set-url origin https://${{ secrets.GITLAB_PASSWORD }}@gitlab.com/MH0386/fdroiddata.git
                git config pull.rebase false
            - name: Verify
              continue-on-error: true
              run: |
                rm renovate.json
                rm -rd .github
                git remote -v
                git fetch origin
                git branch -a
            - name: Update
              continue-on-error: true
              run: |
                git switch com.mh0386.anynotedotai
                git add .
                git commit -m "Update com.MH0386.AnyNoteDotAI.yml"
                # git pull origin com.mh0386.anynotedotai
                git push
