name: Sync with GitLab
on:
    schedule:
        - cron: "0 0 * * *"
    push:
jobs:
    Sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup
              continue-on-error: true
              uses: SvanBoxel/gitlab-mirror-and-ci-action@v0.5
              with:
                args: "https://gitlab.com/MH0386/fdroiddata"
              env:
                # FOLLOW_TAGS: "false"
                # FORCE_PUSH: "false"
                GITLAB_HOSTNAME: "gitlab.com"
                GITLAB_USERNAME: "MH0386"
                GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
                GITLAB_PROJECT_ID: "61681903"
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
